# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Andrew Rikard
email: andrew.rikard@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Thankya Thankya.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://anrikard.github.io" # the base hostname & protocol for your site
twitter_username: anrikard
github_username:  anrikard

# Build settings
markdown: kramdown
